import { Vendor, Booking, Review } from '../types';

export const MOCK_VENDORS: Vendor[] = [
  {
    id: 'v1',
    phoneNumber: '+923001234567',
    role: 'vendor',
    name: 'Ahmed Khan',
    city: 'Karachi',
    cnic: '42101-1234567-1',
    serviceCategories: [
      { id: 'ac', label: 'AC Repair', icon: 'snow-outline' },
      { id: 'refrigerator', label: 'Refrigerator Repair', icon: 'cube-outline' },
    ],
    rating: 4.8,
    totalReviews: 127,
    verified: true,
    isOnline: true,
    profilePhoto: 'https://i.pravatar.cc/150?img=12',
    subscriptionTier: 'premium',
  },
  {
    id: 'v2',
    phoneNumber: '+923001234568',
    role: 'vendor',
    name: 'Hassan Ali',
    city: 'Lahore',
    cnic: '35202-2345678-2',
    serviceCategories: [
      { id: 'plumbing', label: 'Plumbing', icon: 'water-outline' },
      { id: 'water_heater', label: 'Water Heater Repair', icon: 'water-outline' },
    ],
    rating: 4.5,
    totalReviews: 89,
    verified: true,
    isOnline: false,
    profilePhoto: 'https://i.pravatar.cc/150?img=33',
    subscriptionTier: 'basic',
  },
  {
    id: 'v3',
    phoneNumber: '+923001234569',
    role: 'vendor',
    name: 'Bilal Ahmed',
    city: 'Islamabad',
    cnic: '61303-3456789-3',
    serviceCategories: [
      { id: 'electrical', label: 'Electrical', icon: 'flash-outline' },
    ],
    rating: 4.9,
    totalReviews: 203,
    verified: true,
    isOnline: true,
    profilePhoto: 'https://i.pravatar.cc/150?img=51',
    subscriptionTier: 'premium',
  },
  {
    id: 'v4',
    phoneNumber: '+923001234570',
    role: 'vendor',
    name: 'Usman Tariq',
    city: 'Karachi',
    cnic: '42101-4567890-4',
    serviceCategories: [
      { id: 'washing_machine', label: 'Washing Machine Repair', icon: 'settings-outline' },
      { id: 'microwave', label: 'Microwave Repair', icon: 'restaurant-outline' },
    ],
    rating: 4.3,
    totalReviews: 56,
    verified: false,
    isOnline: true,
    profilePhoto: 'https://i.pravatar.cc/150?img=68',
  },
  {
    id: 'v5',
    phoneNumber: '+923001234571',
    role: 'vendor',
    name: 'Imran Malik',
    city: 'Lahore',
    cnic: '35202-5678901-5',
    serviceCategories: [
      { id: 'ac', label: 'AC Repair', icon: 'snow-outline' },
      { id: 'electrical', label: 'Electrical', icon: 'flash-outline' },
    ],
    rating: 4.7,
    totalReviews: 134,
    verified: true,
    isOnline: true,
    profilePhoto: 'https://i.pravatar.cc/150?img=15',
    subscriptionTier: 'premium',
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    customerId: 'c1',
    vendorId: 'v1',
    serviceCategory: { id: 'ac', label: 'AC Repair', icon: 'snow-outline' },
    scheduledDate: '2025-11-05',
    scheduledTime: '10:00 AM',
    status: 'pending',
    address: 'House 123, Street 45, DHA Phase 2, Karachi',
    notes: 'AC not cooling properly',
    createdAt: '2025-11-03T10:00:00Z',
  },
  {
    id: 'b2',
    customerId: 'c1',
    vendorId: 'v3',
    serviceCategory: { id: 'electrical', label: 'Electrical', icon: 'flash-outline' },
    scheduledDate: '2025-10-28',
    scheduledTime: '2:00 PM',
    status: 'completed',
    address: 'House 123, Street 45, DHA Phase 2, Karachi',
    notes: 'Fix electrical wiring issue',
    createdAt: '2025-10-25T08:00:00Z',
  },
  {
    id: 'b3',
    customerId: 'c1',
    vendorId: 'v2',
    serviceCategory: { id: 'plumbing', label: 'Plumbing', icon: 'water-outline' },
    scheduledDate: '2025-10-15',
    scheduledTime: '11:00 AM',
    status: 'completed',
    address: 'House 123, Street 45, DHA Phase 2, Karachi',
    notes: 'Leaking pipe in bathroom',
    createdAt: '2025-10-12T14:00:00Z',
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    bookingId: 'b2',
    customerId: 'c1',
    vendorId: 'v3',
    rating: 5,
    comment: 'Excellent service! Very professional and quick.',
    createdAt: '2025-10-29T10:00:00Z',
    customerName: 'Sara Ahmed',
  },
  {
    id: 'r2',
    bookingId: 'b3',
    customerId: 'c1',
    vendorId: 'v2',
    rating: 4,
    comment: 'Good work, but took a bit longer than expected.',
    createdAt: '2025-10-16T15:00:00Z',
    customerName: 'Ali Khan',
  },
  {
    id: 'r3',
    bookingId: 'other1',
    customerId: 'c2',
    vendorId: 'v1',
    rating: 5,
    comment: 'Ahmed is the best! Fixed my AC in no time.',
    createdAt: '2025-10-20T12:00:00Z',
    customerName: 'Fatima Sheikh',
  },
  {
    id: 'r4',
    bookingId: 'other2',
    customerId: 'c3',
    vendorId: 'v1',
    rating: 4,
    comment: 'Very knowledgeable and friendly.',
    createdAt: '2025-10-10T09:00:00Z',
    customerName: 'Hassan Raza',
  },
];
